//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityNews.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityNews_File
    {
        public int ID { get; set; }
        public string Fk_ID { get; set; }
        public string FileRealName { get; set; }
        public string FilePath { get; set; }
        public string MinPath { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
