//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityNews.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CityNewsEntities : DbContext
    {
        public CityNewsEntities()
            : base("name=CityNewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CityNews_ActitySign> CityNews_ActitySign { get; set; }
        public virtual DbSet<CityNews_BrokeNews> CityNews_BrokeNews { get; set; }
        public virtual DbSet<CityNews_Dict> CityNews_Dict { get; set; }
        public virtual DbSet<CityNews_File> CityNews_File { get; set; }
        public virtual DbSet<CityNews_ActitiesList> CityNews_ActitiesList { get; set; }
    
        public virtual int ChangeCityNews_ActitiesIndex(Nullable<int> currentID, Nullable<int> desID)
        {
            var currentIDParameter = currentID.HasValue ?
                new ObjectParameter("CurrentID", currentID) :
                new ObjectParameter("CurrentID", typeof(int));
    
            var desIDParameter = desID.HasValue ?
                new ObjectParameter("DesID", desID) :
                new ObjectParameter("DesID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeCityNews_ActitiesIndex", currentIDParameter, desIDParameter);
        }
    
        public virtual int ChangeCityNews_BrokeIndex(Nullable<int> currentID, Nullable<int> desID)
        {
            var currentIDParameter = currentID.HasValue ?
                new ObjectParameter("CurrentID", currentID) :
                new ObjectParameter("CurrentID", typeof(int));
    
            var desIDParameter = desID.HasValue ?
                new ObjectParameter("DesID", desID) :
                new ObjectParameter("DesID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeCityNews_BrokeIndex", currentIDParameter, desIDParameter);
        }
    }
}
