//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityNews.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityNews_ActitiesList
    {
        public int ID { get; set; }
        public string IP { get; set; }
        public int IPInt { get; set; }
        public string Leader { get; set; }
        public string Name { get; set; }
        public string Contents { get; set; }
        public string Arrange { get; set; }
        public System.DateTime AddTime { get; set; }
        public int State { get; set; }
        public int Status { get; set; }
        public string FilePath { get; set; }
        public System.DateTime SignEndTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int OrderIndex { get; set; }
        public string Phone { get; set; }
    }
}
