//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityNews.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityNews_ActitySign
    {
        public int Id { get; set; }
        public int Fk_Id { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Ip { get; set; }
        public int IpInt { get; set; }
    }
}
