//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityNews.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityNews_BrokeNews
    {
        public int ID { get; set; }
        public string IP { get; set; }
        public int IPInt { get; set; }
        public string Phone { get; set; }
        public string Contents { get; set; }
        public string FilePath { get; set; }
        public int Type { get; set; }
        public int State { get; set; }
        public System.DateTime Creatime { get; set; }
        public int Status { get; set; }
        public string Explain { get; set; }
        public System.DateTime ExplainTime { get; set; }
        public System.DateTime IficationTime { get; set; }
        public int OrderIndex { get; set; }
        public string Title { get; set; }
    }
}
